### ISSUE TITLE
Date picker flashes when clicking on a label in Chrome

### ISSUE THREAD

**Issue by jmirmina** [bevacqua/rome#102]
On the latest version of Chrome (Version 42.0.2311.135 (64-bit) on Mac 10.10), when you click on a label for an input, the date picker displays for a split second and then disappears. I can occasionally get it to happen in Firefox (37.0.2). It does not happen on the latest version of Safari.

I've encountered the issue both locally and on the [Rome demo page](http://bevacqua.github.io/rome/)

**Comment by bevacqua** [comment]
When your calendar loses focus it's hidden (`blur` event), then you click on the label which focuses the input and displays the calendar again (`focus` event). There really isn't a lot that can be done about this issue because it's kind of a catch-22. I'm open to suggestions on how to solve it though.

**Comment by Young555** [comment]
финансовый документ не исполнено Grait Britain -King's Monako -ПОДПИСЬ ПАНФИЛОВА

**Comment by Astray-git** [comment]
in Firefox (43.0.1) and Safari (9.0.2), click label, the associated input get **focused**, rome doesn't shows up. 
in Chrome (47) date picker displays a second then disappears.

The date picker only show up if I click (focus) the input directly.
