### ISSUE TITLE
Deprecation message on console

### ISSUE THREAD

**Issue by omarfouad** [bevacqua/rome#61]
Whenever I implement rome, I get the two following deprecation message from `moment`:

`Deprecation warning: moment().add(period, number) is deprecated. Please use moment().add(number, period)`

`Deprecation warning: moment().subtract(period, number) is deprecated. Please use moment().subtract(number, period).`

Rome should implement `moment`'s date manipulation as per the documentation here:
http://momentjs.com/docs/#/manipulating/add/

**Comment by bevacqua** [comment]
Are you using the latest version?

**Comment by omarfouad** [comment]
Version 2.0.0? Looks like you just added it half an hour ago as I updated yesterday to 1.2.3.

That was fast. 👍

**Comment by bevacqua** [comment]
Yeah, it fixes the other issue you were having, which was one of the most painful aspects of `rome`

**Comment by omarfouad** [comment]
Good work!

**Comment by mlent** [comment]
Any plans to fix the main deprecation message? This:

https://github.com/bevacqua/rome/blob/28db91a96cb3fa63632e20479b25a822680b7c1f/dist/rome.js#L3065-L3069

Would this be a difficult fix? Or am I getting this message because I'm using the standalone version? Can you advise how I would avoid it? Thank you.

**Comment by bevacqua** [comment]
I'd just ignore it for now
